CREATE DATABASE VENDAS
GO
USE VENDAS

CREATE TABLE CORES (
ID INT PRIMARY KEY,
NOME_COR VARCHAR (100) NOT NULL UNIQUE,

)

ALTER TABLE CORES ADD CONSTRAINT FK_VEICULOS_CORES FOREIGN KEY (ID) REFERENCES VEICULOS(ID)

INSERT INTO CORES (ID, NOME_COR) VALUES (1, 'PRETO')
INSERT INTO CORES (ID, NOME_COR) VALUES (2, 'BRANCO')
INSERT INTO CORES (ID, NOME_COR) VALUES (3, 'VERMELHO')
INSERT INTO CORES (ID, NOME_COR) VALUES (4, 'AZUL')


CREATE TABLE VEICULOS(
ID INT PRIMARY KEY,
DESCRICAO VARCHAR (100),
DATA_CRIACAO DATE NOT NULL,
TIPO_MOTOR DECIMAL NOT NULL,
VALOR SMALLMONEY NULL,
VENDIDO BIT NOT NULL,
ID_CORES INT REFERENCES CORES (ID)

)


INSERT INTO VEICULOS (ID, DESCRICAO, DATA_CRIACAO, TIPO_MOTOR, VALOR, VENDIDO, ID_CORES) VALUES (1, 'CHEVROLET', '2022-12-10', 1.4, 15000, 0, 3)
INSERT INTO VEICULOS (ID, DESCRICAO, DATA_CRIACAO, TIPO_MOTOR, VALOR, VENDIDO, ID_CORES) VALUES (2, 'FORD', '2020-09-03', 2.0, 22000, 0, 2)
INSERT INTO VEICULOS (ID, DESCRICAO, DATA_CRIACAO, TIPO_MOTOR, VALOR, VENDIDO, ID_CORES) VALUES(3, 'TOYOTA', '2015-04-25', 1.0, 10000, 1, 1)
INSERT INTO VEICULOS (ID, DESCRICAO, DATA_CRIACAO, TIPO_MOTOR, VALOR, VENDIDO, ID_CORES) VALUES(4, 'HYUNDAI', '2023-09-25', 2.0 , 120000, 1, 1)
INSERT INTO VEICULOS (ID, DESCRICAO, DATA_CRIACAO, TIPO_MOTOR, VALOR, VENDIDO, ID_CORES) VALUES(5, 'HONDA', '2024-09-25', 2.0 , 85000, 0, (SELECT ID FROM CORES WHERE NOME_COR = 'AZUL' ))



DROP TABLE VEICULOS




