CREATE DATABASE SEMANA_07
GO
USE SEMANA_07

-- EXERCICÍO 01
CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (20),
TELEFONE VARCHAR (11),
ENDERECO VARCHAR (MAX),
)


-- EXERCICÍO 02
INSERT INTO CLIENTES (NOME, TELEFONE, ENDERECO) 
	VALUES ('VINICIUS SILVA', '987654', 'RUA GIRASSOL'),
		   ('MARIA ANTONIA', '123456', 'RUA ROSAS'),
		   ('MARCUS VINICIUS', '654321', 'RUA ITAJAI')


-- EXERCICÍO 03
SELECT * FROM CLIENTES

-- EXERCICÍO 04
SELECT CLIENTES.ID_CLIENTE FROM CLIENTES
SELECT * FROM CLIENTES WHERE ID_CLIENTE = 1

-- EXERCICÍO 05
SELECT * FROM CLIENTES WHERE NOME LIKE '%MA%'

-- EXERCICÍO 06
--- IDENTIFICAR CLIENTE
SELECT * FROM CLIENTES WHERE NOME LIKE '%MARCUS%'
--- ATUALIZAR DADOS
UPDATE CLIENTES SET ENDERECO = 'RUA DO LIMÃO' WHERE ID_CLIENTE = 3

--EXERCICIO 07
--- EXCLUÍ O ID ERRADO, ERA O CLIENTE 2... 
DELETE CLIENTES WHERE ID_CLIENTE = 1


